added R code and the setosa.csv file created with code
Added files via upload because for some unknown reason (unknown to me) it didn't want to push 

jic this is the error I was getting 
error: src refspec master does not match any.
error: failed to push some refs to 'https://github.com/alebronND/Biocomputing2020_Tutorial09.git'